config/routes.rb
Watrcoolr::Application.routes.draw do
  # devise for routes
  devise_for :users

  # Room routes
  resources :rooms, only: [:index, :new] do
    collection { get :events }
  end
  get '/rooms/:id', to: "rooms#watrcoolr", as: "room"
  post '/rooms/add_message', to: 'rooms#add_message'
  post '/rooms/create', to: 'rooms#create'
  post '/rooms/create_message', to: 'rooms#create_message'
  post '/rooms/clear_msg_content', to: 'rooms#clear_msg_content'

  # messages routes
  resources :messages

  post '/messages/add_message', to: 'messages#add_message'
  resources :texts, controller: 'messages', msg_type: 'Text' 
  resources :videos, controller: 'messages', msg_type: 'Video' 
  resources :images, controller: 'messages', msg_type: 'Image'

  # Authenticated Root
  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end

  # root url
  # root :to => 'home#index'
  root :to => 'home#landing'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.all
    @all_tribunals = Tribunal.all
    @user = current_user
    @current_user_rooms = current_user.rooms
    @tribunals = current_user.tribunals
    @current_user_tribunals = []

    current_user.tribunals.each do |a|

    	trib_info = []
    	room = Room.find(a.room_id)
    	trib_info << a
    	trib_info << room.name
    	# trib_info << room.users
    	@current_user_tribunals << trib_info
    end
  end

  def landing
  	render :layout 	=> false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render "test/nav" %>
<div class="home container">
  <div class="row">
   
    <div class="col-md-3 col-md-offset-1">
        <% if user_signed_in? %>
        <h1 class="home-user"><%= @user.username %></h1>
        <hr>
        <div class="row">
            <div class="col-md-6">
              <p>Number of Rooms: <%= @user.rooms.length %></p>
                <p>Messages Sent: <%= @user.messages.length %></p>
                <p><%= link_to "Profile Settings", controller: "devise/registrations", action: "edit", class: "article"%></p>
            </div>
            <div class="col-md-6">
            </div>
        </div>
        <% end %>
    </div>

    <div class="col-md-8">
      <h2>Rooms</h2>
      <%= link_to 'Create a Room', new_room_path %>
      <hr>
      <div class="rooms">
        <% if @current_user_rooms.length == 0 %>
          <p>You're not a part of any rooms! Create one, or, make some friends!</p>
        <% elsif @current_user_rooms.length > 0 %>
          <ul id="room-list" class="roomlist list list-unstyled">
            <% @current_user_rooms.each do |room| %>
              <li>
                <h3><%= link_to room.name, room_path(room) %></h3>
                <p>Population: <%= room.users.length %> / Messages Sent: <%= room.messages.length %></p>
              </li>
              <hr>
            <% end %>
          </ul>
        <% else %>
          <ul id="room-list-empty" class="roomlist"> 
            <li>No rooms exist yet. Create one!</li> 
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-md-3">
      <h2>Tribunals</h2>
      <hr>
      <div class="tribs">
        <% if @user.tribunals.length > 0 %>
          <% @user.tribunals.each do |tribunal| %>
          <h4><%= tribunal.title %></h4>
          <ul id="trib-list" class="triblist list list-unstyled">
            <% if tribunal.applicant_id == @user.id %>
              <ul class="votes-list">
                <li><label for="votes_for">Votes For:</label><%= tribunal.votes_for %></li>
                <li><label for="votes_against">Votes Against:</label><%= tribunal.votes_against %></li>
              </ul>
            <% else %>
              <input type="hidden" name="tribunal_id" value="<%= tribunal.id %>" />
              <button id="vote-for" class="vote-button">FOR</button>
              <button id="vote-against" class="vote-button">AGAINST</button>
            <% end %>
          <% end %>
        </ul>
      <% end %>

      </div>
    </div>
  </div><!-- /.row -->
</div><!-- /.container -->

app/views/home/landing.html.erb
<%= stylesheet_link_tag :bootstrap%>

<style>
body {
	color: #71B8FF;
	background: -webkit-radial-gradient(#D3D3D3,  white); /* Safari 5.1 to 6.0 */
	background: -o-radial-gradient(#D3D3D3,  white); /* For Opera 11.6 to 12.0 */
	background: -moz-radial-gradient(#D3D3D3,  white); /* For Firefox 3.6 to 15 */
	background: radial-gradient(#D3D3D3,  white); /* Standard syntax */
}	

.landing {
	position: absolute;
	height: 800px;
	width: 800px;
	top: 50%;
	left: 50%;
	margin-left: -400px;
	margin-top: -400px;
}

.landing h1 {
	margin-top: 25%;
	font-size: 8em;
	font-weight: bolder;
	letter-spacing: .1em;
}

.landing h3 {
	color: white;
	font-size: 3em;
	margin-top: 1%;
	margin-bottom: 15%; 
}

.landing a {
	border-radius: 4px;
	padding: 20px 40px;
	font-size: 2em;
	color: white;
	background: #71B8FF;
	text-decoration: none;
}

.landing a:hover {
	background: white;
	color: #71B8FF; 
}

@media (max-width: 650px) {
  .landing h1 {
  	font-size: 4.75em;
  }
}
</style>


<div class="container">
<div class="landing text-center">
	<h1>WatrCoolr</h1>
	<h3>Ephemeral Group Chat</h3>
	<%= link_to "Login", controller: "devise/sessions", action: "new", class: "article"%>
	<%= link_to "Sign Up", controller: "devise/registrations", action: "new", class: "article" %>
</div>
</div>